# -*- coding: utf-8 -*-
"""cv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SATBFJvDQRoUynXuaj0rjzO3MBuUCJMB
"""

import urllib.request, os

IMAGE_DIR = "opencv_images"
os.makedirs(IMAGE_DIR, exist_ok=True)

urls = {
    "lena.jpg":        "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg",
    "baboon.jpg":      "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/baboon.jpg",
    "fruits.jpg":      "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/fruits.jpg",
    "opencv-logo.png": "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/opencv-logo.png",
    "sudoku.png":      "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/sudoku.png",
}

for fname, url in urls.items():
    path = os.path.join(IMAGE_DIR, fname)
    if not os.path.exists(path):
        urllib.request.urlretrieve(url, path)
        print(f" Downloaded: {fname}")
    else:
        print(f"Already exists: {fname}")

"""task 1"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

IMAGE_DIR = "opencv_images"

image_files = {
    "lena.jpg": "JPG", "baboon.jpg": "JPG", "fruits.jpg": "JPG",
    "opencv-logo.png": "PNG", "sudoku.png": "PNG",
}

images = {}
for fname, fmt in image_files.items():
    path = os.path.join(IMAGE_DIR, fname)
    img = cv2.imread(path)
    if img is None:
        print(f" Could not load {fname}")
        continue
    H, W, C = img.shape
    images[fname] = img
    print(f" {fname} ({fmt})  H={H}, W={W}, C={C}  dtype={img.dtype}  Valid: {'yes' if C==3 else 'no'}")

# Visualise
fig, axes = plt.subplots(1, len(images), figsize=(18, 4))
fig.patch.set_facecolor("#0f0f1a")
fig.suptitle("TASK 1 — Loaded Images & H×W×C Validation", color="white", fontsize=13, fontweight="bold")

for ax, (fname, img) in zip(axes, images.items()):
    H, W, C = img.shape
    ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    ax.set_title(f"{fname}\n{H}×{W}×{C}", color="white", fontsize=8)
    ax.axis("off")

plt.tight_layout()
plt.show()  # ← savefig ni jagah show() use karo notebook ma

"""task 2"""

# TASK 2 — Resizing & Pixel-Level Difference
import cv2
import numpy as np
import matplotlib.pyplot as plt

img_bgr = images["lena.jpg"]  # Task 1 wala images dict use hoga
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
H, W    = img_bgr.shape[:2]

# Down-scale then Up-scale (4x down to show interpolation difference clearly)
small_h, small_w = H // 4, W // 4

small_linear = cv2.resize(img_bgr, (small_w, small_h), interpolation=cv2.INTER_LINEAR)
small_cubic  = cv2.resize(img_bgr, (small_w, small_h), interpolation=cv2.INTER_CUBIC)

up_linear = cv2.resize(small_linear, (W, H), interpolation=cv2.INTER_LINEAR)
up_cubic  = cv2.resize(small_cubic,  (W, H), interpolation=cv2.INTER_CUBIC)

# Pixel-level absolute difference
diff      = cv2.absdiff(up_linear, up_cubic)
diff_norm = cv2.normalize(diff, None, 0, 255, cv2.NORM_MINMAX)

# MSE & PSNR calculate karo
mse  = np.mean((up_linear.astype(float) - up_cubic.astype(float)) ** 2)
psnr = 10 * np.log10(255**2 / mse) if mse > 0 else float("inf")

print(f" Original size   : {W}×{H}")
print(f" Downscaled to   : {small_w}×{small_h}")
print(f" Upscaled back   : {W}×{H}")
print(f" MSE  (L vs C)   : {mse:.4f}")
print(f" PSNR (L vs C)   : {psnr:.2f} dB")

# Visualise
fig, axes = plt.subplots(1, 4, figsize=(18, 5))
fig.patch.set_facecolor("#0f0f1a")
fig.suptitle("TASK 2 — INTER_LINEAR vs INTER_CUBIC Interpolation",
             color="white", fontsize=13, fontweight="bold")

panels = [
    (img_rgb,                                     "Original"),
    (cv2.cvtColor(up_linear, cv2.COLOR_BGR2RGB),  "INTER_LINEAR\n(upscaled)"),
    (cv2.cvtColor(up_cubic,  cv2.COLOR_BGR2RGB),  "INTER_CUBIC\n(upscaled)"),
    (cv2.cvtColor(diff_norm, cv2.COLOR_BGR2RGB),  f"Pixel Difference\nMSE={mse:.3f}  PSNR={psnr:.1f}dB"),
]

for ax, (panel_img, title) in zip(axes, panels):
    ax.imshow(panel_img)
    ax.set_title(title, color="white", fontsize=10)
    ax.axis("off")

plt.tight_layout()
plt.show()

"""task 3

"""

# TASK 3 — Rotation (45° & 90°) Without Cropping Corners
import cv2
import numpy as np
import matplotlib.pyplot as plt

img_bgr = images["fruits.jpg"]  # Task 1 wala images dict
H, W    = img_bgr.shape[:2]

# ── Helper function — canvas expand karo taaki corners crop na hon ──
def rotate_no_crop(image, angle_deg):
    h, w    = image.shape[:2]
    cx, cy  = w / 2, h / 2

    # Rotation matrix compute karo
    M = cv2.getRotationMatrix2D((cx, cy), angle_deg, 1.0)

    cos_a = abs(M[0, 0])
    sin_a = abs(M[0, 1])

    # Naya canvas size calculate karo
    new_w = int(h * sin_a + w * cos_a)
    new_h = int(h * cos_a + w * sin_a)

    # Matrix shift karo — centre adjust karo naye canvas ke liye
    M[0, 2] += (new_w / 2) - cx
    M[1, 2] += (new_h / 2) - cy

    rotated = cv2.warpAffine(image, M, (new_w, new_h),
                             flags=cv2.INTER_CUBIC,
                             borderMode=cv2.BORDER_CONSTANT,
                             borderValue=(255, 255, 255))
    return rotated, M

# Rotate karo
rot45,  M45  = rotate_no_crop(img_bgr,  45)
rot90,  M90  = rotate_no_crop(img_bgr,  90)
rot_n45, _   = rotate_no_crop(img_bgr, -45)

print(f" Original size   : {W}×{H}")
print(f" After  45°      : {rot45.shape[1]}×{rot45.shape[0]}")
print(f" After  90°      : {rot90.shape[1]}×{rot90.shape[0]}")
print(f" After -45°      : {rot_n45.shape[1]}×{rot_n45.shape[0]}")
print(f"\n Rotation Matrix (45°):\n{M45}")

# Visualise
fig, axes = plt.subplots(1, 4, figsize=(18, 5))
fig.patch.set_facecolor("#0f0f1a")
fig.suptitle("TASK 3 — Rotation via Transformation Matrix (No Corner Cropping)",
             color="white", fontsize=12, fontweight="bold")

imgs   = [img_bgr, rot45, rot90, rot_n45]
titles = ["Original", "Rotated 45°", "Rotated 90°", "Rotated -45°"]

for ax, im, t in zip(axes, imgs, titles):
    ax.imshow(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))
    ax.set_title(t, color="white", fontsize=10)
    ax.axis("off")

plt.tight_layout()
plt.show()

"""task 4"""

# TASK 4 — ROI Crop & Horizontal / Vertical Flips
import cv2
import numpy as np
import matplotlib.pyplot as plt

img_bgr = images["baboon.jpg"]  # Task 1 wala images dict
H, W    = img_bgr.shape[:2]

# ── ROI — central 40% region crop karo ──
y1 = int(H * 0.30);  y2 = int(H * 0.70)
x1 = int(W * 0.30);  x2 = int(W * 0.70)

roi = img_bgr[y1:y2, x1:x2].copy()

# ── Flips ──
flip_h = cv2.flip(roi,  1)   # flipCode=1  → Horizontal flip
flip_v = cv2.flip(roi,  0)   # flipCode=0  → Vertical flip
flip_b = cv2.flip(roi, -1)   # flipCode=-1 → Both axes flip

print(f" Original size   : {W}×{H}")
print(f"  ROI coords      : x=[{x1}, {x2}]  y=[{y1}, {y2}]")
print(f" ROI size        : {roi.shape[1]}×{roi.shape[0]}")
print(f"  Flip H (code=1) : {flip_h.shape}")
print(f"  Flip V (code=0) : {flip_v.shape}")
print(f"  Flip B (code=-1): {flip_b.shape}")

# ROI rectangle original image pe draw karo (context ke liye)
viz_orig = img_bgr.copy()
cv2.rectangle(viz_orig, (x1, y1), (x2, y2), (0, 255, 0), 3)
cv2.putText(viz_orig, "ROI", (x1 + 5, y1 + 25),
            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)

# Visualise
fig, axes = plt.subplots(1, 5, figsize=(20, 4))
fig.patch.set_facecolor("#0f0f1a")
fig.suptitle("TASK 4 — ROI Extraction & Flip Operations",
             color="white", fontsize=12, fontweight="bold")

panels = [
    (viz_orig, "Original + ROI Box"),
    (roi,      "Extracted ROI"),
    (flip_h,   "Horizontal Flip\n(flipCode=1)"),
    (flip_v,   "Vertical Flip\n(flipCode=0)"),
    (flip_b,   "Both Axes Flip\n(flipCode=-1)"),
]

for ax, (im, t) in zip(axes, panels):
    ax.imshow(cv2.cvtColor(im, cv2.COLOR_BGR2RGB))
    ax.set_title(t, color="white", fontsize=9)
    ax.axis("off")

plt.tight_layout()
plt.show()

"""task 5"""

# TASK 5 — Color Space Conversion Module (BGR → Grayscale & HSV)
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# ── Conversion function ──
def convert_color_spaces(bgr_image):
    gray = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2GRAY)
    hsv  = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2HSV)
    return gray, hsv

# ── Saari images pe conversion apply karo ──
print("=" * 55)
print("  TASK 5 — Color Space Analysis")
print("=" * 55)

for fname, img_bgr in images.items():
    gray, hsv    = convert_color_spaces(img_bgr)
    H_ch, S_ch, V_ch = cv2.split(hsv)

    print(f"\n    {fname}")
    print(f"      BGR  shape : {img_bgr.shape}")
    print(f"      Gray shape : {gray.shape}  (single channel)")
    print(f"      HSV  shape : {hsv.shape}")
    print(f"      H channel  : mean={H_ch.mean():.1f}, std={H_ch.std():.1f}")
    print(f"      S channel  : mean={S_ch.mean():.1f}, std={S_ch.std():.1f}")
    print(f"      V channel  : mean={V_ch.mean():.1f}, std={V_ch.std():.1f}")

# ── Detailed visualisation — lena.jpg ──
img_bgr      = images["lena.jpg"]
img_rgb      = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
gray, hsv    = convert_color_spaces(img_bgr)
H_ch, S_ch, V_ch = cv2.split(hsv)
B, G, R          = cv2.split(img_bgr)

# Histogram helper
def channel_hist(channel):
    return cv2.calcHist([channel], [0], None, [256], [0, 256]).flatten()

# ── Figure layout ──
fig = plt.figure(figsize=(20, 10), facecolor="#0f0f1a")
fig.suptitle("TASK 5 — Color Space Conversion: BGR → Grayscale & HSV\nSource: lena.jpg",
             color="white", fontsize=13, fontweight="bold")

gs = gridspec.GridSpec(3, 5, figure=fig, hspace=0.45, wspace=0.3)

def show(ax, im, cmap=None, title=""):
    ax.imshow(im, cmap=cmap)
    ax.set_title(title, color="white", fontsize=9)
    ax.axis("off")

# Row 0 — Converted images
show(fig.add_subplot(gs[0, 0]), img_rgb,             title="BGR Source\n(RGB view)")
show(fig.add_subplot(gs[0, 1]), gray,  cmap="gray",  title="Grayscale")
show(fig.add_subplot(gs[0, 2]), H_ch,  cmap="hsv",   title="HSV — H\n(Hue)")
show(fig.add_subplot(gs[0, 3]), S_ch,  cmap="YlOrRd",title="HSV — S\n(Saturation)")
show(fig.add_subplot(gs[0, 4]), V_ch,  cmap="gray",  title="HSV — V\n(Value/Brightness)")

# Row 1 — BGR channels + histograms
show(fig.add_subplot(gs[1, 0]), R, cmap="Reds",   title="BGR — R channel")
show(fig.add_subplot(gs[1, 1]), G, cmap="Greens", title="BGR — G channel")
show(fig.add_subplot(gs[1, 2]), B, cmap="Blues",  title="BGR — B channel")

ax_gray_hist = fig.add_subplot(gs[1, 3])
ax_gray_hist.fill_between(range(256), channel_hist(gray), color="#aaaaaa", alpha=0.8)
ax_gray_hist.set_title("Gray Histogram", color="white", fontsize=9)
ax_gray_hist.tick_params(colors="white", labelsize=7)
ax_gray_hist.set_facecolor("#1a1a2e")

ax_rgb_hist = fig.add_subplot(gs[1, 4])
for ch_data, col in zip([R, G, B], ["#ff4444", "#44ff44", "#4488ff"]):
    ax_rgb_hist.plot(channel_hist(ch_data), color=col, alpha=0.8, linewidth=1)
ax_rgb_hist.set_title("RGB Channel Histograms", color="white", fontsize=9)
ax_rgb_hist.tick_params(colors="white", labelsize=7)
ax_rgb_hist.set_facecolor("#1a1a2e")

# Row 2 — HSV histograms
hsv_data   = [H_ch,      S_ch,          V_ch]
hsv_labels = ["Hue",     "Saturation",  "Value"]
hsv_colors = ["#ff9500", "#ff3399",     "#33ccff"]

for i, (ch, lbl, clr) in enumerate(zip(hsv_data, hsv_labels, hsv_colors)):
    ax = fig.add_subplot(gs[2, i + 1])
    ax.fill_between(range(256), channel_hist(ch), color=clr, alpha=0.75)
    ax.set_title(f"HSV — {lbl} Histogram", color="white", fontsize=8)
    ax.tick_params(colors="white", labelsize=7)
    ax.set_facecolor("#1a1a2e")

plt.tight_layout()
plt.show()

