# -*- coding: utf-8 -*-
"""mini_project_cv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2YIccrxay_ouo9K3ZgMQ-WT9D2_0_j_
"""

# STEP 1 — Download sample images (X-ray/MRI jevi grayscale images)
import urllib.request, os

IMAGE_DIR = "medical_scans"
os.makedirs(IMAGE_DIR, exist_ok=True)

urls = {
    "xray_hand.jpg":    "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/hand.jpg",
    "mri_brain.jpg":    "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/fruits.jpg",
    "scan_lena.jpg":    "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg",
    "scan_baboon.jpg":  "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/baboon.jpg",
    "xray_sudoku.png":  "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/sudoku.png",
    "mri_logo.png":     "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/opencv-logo.png",
}

for fname, url in urls.items():
    path = os.path.join(IMAGE_DIR, fname)
    try:
        urllib.request.urlretrieve(url, path)
        print(f" Downloaded: {fname}")
    except:
        print(f"  Skipped (not found): {fname}")

"""MODULE 1 — Load & Inventory"""

def load_scans(folder):
    supported = ("*.jpg", "*.jpeg", "*.png", "*.bmp", "*.tiff")
    paths = []
    for ext in supported:
        paths.extend(glob.glob(os.path.join(folder, ext)))

    scans = {}
    print("\n" + "="*60)
    print("  MODULE 1 — Scan Inventory")
    print("="*60)
    for p in sorted(paths):
        img = cv2.imread(p)
        if img is None:
            continue
        fname = os.path.basename(p)
        scans[fname] = img
        H, W, C = img.shape
        print(f"   {fname:25s}  {W:4d}×{H:4d}  C={C}  {img.dtype}")
    print(f"\n  Total scans loaded: {len(scans)}")
    return scans

"""MODULE 2 — Interpolation Selector


Smart selection based on scale factor
"""

import cv2, numpy as np, matplotlib.pyplot as plt, os, glob

IMAGE_DIR  = "medical_scans"
OUTPUT_DIR = "normalized_scans"
os.makedirs(OUTPUT_DIR, exist_ok=True)

TARGET = (256, 256)

# ── Load all images ──────────────────────────────────────────
paths  = glob.glob(IMAGE_DIR + "/*.jpg") + glob.glob(IMAGE_DIR + "/*.png")
scans  = {os.path.basename(p): cv2.imread(p) for p in sorted(paths)}

print(f" {len(scans)} scans loaded\n")
for fname, img in scans.items():
    H, W = img.shape[:2]
    print(f"   {fname:25s} → {W}×{H}")

# ── Process each scan ────────────────────────────────────────
processed = {}
for fname, img in scans.items():
    H, W = img.shape[:2]

    # Smart interpolation select karo
    if (256*256) >= (H*W):
        interp, iname = cv2.INTER_CUBIC, "INTER_CUBIC (upscale)"
    else:
        interp, iname = cv2.INTER_AREA,  "INTER_AREA  (downscale)"

    # Step 1 — Resize
    resized = cv2.resize(img, TARGET, interpolation=interp)

    # Step 2 — Grayscale
    gray    = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)

    # Step 3 — CLAHE (contrast enhance)
    clahe     = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    enhanced  = clahe.apply(gray)

    # Step 4 — Normalize [0,1] then back to uint8
    final = (enhanced.astype(np.float32) / 255.0 * 255).astype(np.uint8)

    # Save
    save_path = os.path.join(OUTPUT_DIR, f"norm_{fname.split('.')[0]}.png")
    cv2.imwrite(save_path, final)

    processed[fname] = {
        "original": img,
        "gray":     gray,
        "enhanced": enhanced,
        "final":    final,
        "interp":   iname,
        "orig_size": f"{W}×{H}"
    }

# ── Visualisation ────────────────────────────────────────────
n   = len(processed)
fig, axes = plt.subplots(n, 4, figsize=(16, n * 3.2))
fig.patch.set_facecolor("#050510")
fig.suptitle("Automated Medical Scan Normalizer\nOriginal  |  Grayscale  |  CLAHE Enhanced  |  Final Normalized",
             color="white", fontsize=13, fontweight="bold", y=1.01)

col_titles = ["Original", "Grayscale", "CLAHE Enhanced", "Final (256×256)"]

for row, (fname, r) in enumerate(processed.items()):
    orig  = cv2.cvtColor(r["original"], cv2.COLOR_BGR2RGB)
    steps = [orig, r["gray"], r["enhanced"], r["final"]]
    cmaps = [None, "gray", "gray", "gray"]

    for col, (im, cm, ct) in enumerate(zip(steps, cmaps, col_titles)):
        ax = axes[row][col] if n > 1 else axes[col]
        ax.imshow(im, cmap=cm)
        if row == 0:
            ax.set_title(ct, color="#a78bfa", fontsize=11, fontweight="bold")
        if col == 0:
            ax.set_ylabel(f"{fname[:18]}\n{r['orig_size']}\n{r['interp']}",
                          color="white", fontsize=7, rotation=0, labelpad=75)
        ax.axis("off")

plt.tight_layout()
plt.show()

# ── Summary print ─────────────────────────────────────────────
print("\n" + "="*55)
print("  PROCESSING SUMMARY")
print("="*55)
for fname, r in processed.items():
    print(f"\n   {fname}")
    print(f"     Original  : {r['orig_size']}")
    print(f"     Final     : 256×256 Grayscale")
    print(f"     Interp.   : {r['interp']}")
    print(f"     Saved   : norm_{fname.split('.')[0]}.png")

print(f"\n All scans saved in → {OUTPUT_DIR}/")

